// <auto-generated />
using System;
using Audit_Service.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Audit_Service.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260913140306_Create_Migration")]
    partial class Create_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Audit_Service.API.Infrastructure.Persistence.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccuredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("ActorId");

                    b.HasIndex("Properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "gin");

                    b.HasIndex("WorkId");

                    b.ToTable("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
